### ISSUE TITLE
 Undefined Method `new' for Archive:Module

### ISSUE THREAD

**Issue by franklinwise** [chef-cookbooks/libarchive#8]
Clean install of ChefDK 0.4 on Ubuntu 14.04
Issue similiar to: https://github.com/burtlo/ark/issues/92

```
    NoMethodError
    -------------
    undefined method `new' for Archive:Module

     Cookbook Trace:
   ---------------
    /var/chef/cookbooks/libarchive/libraries/helper.rb:37:in `block in extract'
    /var/chef/cookbooks/libarchive/libraries/helper.rb:36:in `chdir'
     /var/chef/cookbooks/libarchive/libraries/helper.rb:36:in `extract'
     /var/chef/cookbooks/libarchive/providers/file.rb:18:in `block in class_from_file'
```

**Comment by iennae** [comment]
Hi! This cookbook has been moved into the purview of the Community Engineering team here at Chef, and I've taken a look at it. There looks to have been an issue right around the release of Chef 12.0 that was resolved with Chef 12.1. I've also made some other (minor) changes that I'll be pushing to the repo, but the cookbook as is will work with Ubuntu 14.04 and a modern chef-client. It does require an apt-update to happen during the compile phase so in your wrapper cookbook:

> apt_update 'update' do
> end.run_action(:update) if platform_family?('debian')

before using resources from this cookbook.
